apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logs
resources:
  - statefulset.yaml
  - service.yaml
configMapGenerator:
  - name: log-storage-config
    files:
      - configuration.yaml
