apiVersion: v1
kind: Service
metadata:
  name: log-storage
  labels:
    app.kubernetes.io/name: log-storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: log-storage
  ports:
    - name: http
      port: 3100
      targetPort: http
