apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-gateway
  namespace: auth
  labels:
    app: auth-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-gateway
  template:
    metadata:
      labels:
        app: auth-gateway
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: auth-gateway
          image: authelia/authelia:4.38.8
          imagePullPolicy: IfNotPresent
          command:
            - authelia
          args:
            - --config=/configuration.yml
          ports:
            - name: http
              containerPort: 9091
          env:
            - name: X_AUTHELIA_CONFIG
              value: /configuration.yml
            - name: X_AUTHELIA_CONFIG_FILTERS
              value: template
            - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
              value: /app/secrets/JWT_SECRET
            - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
              value: /app/secrets/OIDC_HMAC_SECRET
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /app/secrets/SESSION_SECRET
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /app/secrets/STORAGE_ENCRYPTION_KEY
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
              value: /app/secrets/LDAP_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /configuration.yml
              subPath: configuration.yaml
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
            - name: data
              mountPath: /var/lib/authelia
      volumes:
        - name: config
          configMap:
            name: auth-gateway-config
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: data
          persistentVolumeClaim:
            claimName: auth-gateway-data
        - name: secrets
          secret:
            secretName: auth-gateway-secrets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-gateway-data
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
