apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: auth-gateway-config
    files:
      - configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
