apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: auth
  labels:
    app: ldap
spec:
  selector:
    app: ldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP

