apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-cert
spec:
  commonName: metrics.0x42labs.net
  dnsNames:
  - metrics.0x42labs.net
  duration: 8760h
  issuerRef:
    kind: ClusterIssuer
    name: internal-ca-issuer
  renewBefore: 720h
  secretName: metrics-tls
