apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-log-collector
  labels:
    app.kubernetes.io/name: log-collector
    app.kubernetes.io/component: node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: log-collector
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: log-collector
        app.kubernetes.io/component: node
    spec:
      serviceAccountName: log-collector
      containers:
        - name: log-collector
          image: docker.io/timberio/vector:0.56.0-debian
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/vector/node-configuration.toml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/vector
              readOnly: true
            - name: var-log
              mountPath: /var/log
              readOnly: true
            - name: run-log-journal
              mountPath: /run/log/journal
              readOnly: true
            - name: data
              mountPath: /var/lib
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: node-log-collector-config
        - name: var-log
          hostPath:
            path: /var/log
            type: Directory
        - name: run-log-journal
          hostPath:
            path: /run/log/journal
            type: Directory
        - name: data
          emptyDir: {}
