apiVersion: v1
kind: Service
metadata:
  name: dhcp
  annotations:
    metallb.io/address-pool: dhcp-relay-address
    metallb.io/loadBalancerIPs: 10.0.10.71
  labels:
    app.kubernetes.io/name: dhcp
    app.kubernetes.io/part-of: network
    app.kubernetes.io/component: dhcp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dhcp
    app.kubernetes.io/part-of: network
    app.kubernetes.io/component: dhcp
  ports:
    - name: dhcp
      port: 67
      targetPort: dhcp
      protocol: UDP
