apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/kyle-blair/homelab-cluster.git
    targetRevision: main
    path: apps/auth-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
