apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 78.1.0
    helm:
      releaseName: monitoring
      values: |
        grafana:
          grafana.ini:
            server:
              root_url: https://observability.0x42labs.net
            security:
              disable_initial_admin_creation: true
            auth.generic_oauth:
              enabled: true
              name: Auth Gateway
              allow_sign_up: true
              client_id: grafana
              scopes: openid profile email groups
              auth_url: https://auth.0x42labs.net/api/oidc/authorization
              token_url: https://auth.0x42labs.net/api/oidc/token
              api_url: https://auth.0x42labs.net/api/oidc/userinfo
              use_pkce: true
              email_attribute_path: email
              login_attribute_path: preferred_username
              name_attribute_path: name
              role_attribute_path: contains(groups[*], 'admins') && 'GrafanaAdmin' || 'Viewer'
              allow_assign_grafana_admin: true
              tls_client_ca: /etc/grafana/trust/ca-certificates.crt
          extraConfigmapMounts:
            - name: internal-ca-bundle
              mountPath: /etc/grafana/trust/ca-certificates.crt
              subPath: ca-certificates.crt
              configMap: internal-ca-bundle
              readOnly: true
          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
