apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.0x42labs.net
  admin.enabled: "false"
  oidc.config: |
    name: Auth Gateway
    issuer: https://auth.0x42labs.net
    clientID: argocd
    enablePKCEAuthentication: true
    requestedScopes:
      - openid
      - profile
      - email
      - groups
